
local_backend: true
backend:
  name: git-gateway
  branch: main

media_folder: public/images
public_folder: /images

collections:
  - name: "home"
    label: "Homepage"
    files:
      - label: "Homepage"
        name: "home"
        file: "content/home.json"
        fields:
          - { label: "Titel", name: "titel", widget: "string" }
          - { label: "Untertitel", name: "untertitel", widget: "string" }
          - { label: "Einleitungstext", name: "intro", widget: "text" }

  - name: "ueber"
    label: "Über mich"
    files:
      - label: "Über mich"
        name: "ueber"
        file: "content/ueber.json"
        fields:
          - label: "Absätze"
            name: "absaetze"
            widget: "list"
            field: { label: "Absatz", name: "absatz", widget: "text" }


  - name: "kontakt"
    label: "Kontakt"
    files:
      - label: "Kontakt"
        name: "kontakt"
        file: "content/kontakt.json"
        fields:
          - { label: "Header", name: "header", widget: "string" }
          - { label: "Intro", name: "intro", widget: "text" }
          - { label: "E-Mail", name: "email", widget: "string" }
          - { label: "LinkedIn URL", name: "linkedin", widget: "string" }
          - { label: "LinkedIn Text", name: "linkedintxt", widget: "string" }

  - name: "angebot"
    label: "Angebot"
    files:
      - label: "Angebot"
        name: "angebot"
        file: "content/angebot.json"
        fields:
          - label: "Angebote"
            name: "angebote"
            widget: "list"
            fields:
              - { label: "Titel", name: "titel", widget: "string" }
              - { label: "Text", name: "text", widget: "text" }

  - name: "referenzen"
    label: "Referenzen"
    files:
      - label: "Referenzen"
        name: "referenzen"
        file: "content/referenzen.json"
        fields:
          - label: "Referenzen"
            name: "referenzen"
            widget: "list"
            fields:
              - { label: "Titel", name: "titel", widget: "string" }
              - { label: "Medium", name: "medium", widget: "string" }
              - { label: "Beschreibung", name: "beschreibung", widget: "text" }
              - label: "Typ"
                name: "typ"
                widget: "select"
                options: ["link", "pdf", "video", "audio", "bild"]
              - { label: "URL", name: "url", widget: "string", required: false }
              - { label: "Embed / Medienpfad", name: "embed", widget: "string", required: false }

